// Mock data for episodes and learning content
export const episodes = [
  {
    id: "1",
    title: 'Budget Basics',
    status: 'Completed' as const,
    concepts: ['Income', 'Expenses', '50/30/20 Rule'],
    xpReward: 150,
    estimatedTime: '15 min',
    assigned: true,
    classStatus: 'Completed' as const,
    dueDate: '2024-02-15',
  },
  {
    id: "2",
    title: 'Saving Strategies',
    status: 'In progress' as const,
    concepts: ['Emergency Fund', 'High-Yield Savings', 'Compound Interest'],
    xpReward: 200,
    estimatedTime: '20 min',
    assigned: true,
    classStatus: 'In Progress' as const,
    dueDate: '2024-02-20',
  },
  {
    id: "3",
    title: 'Credit Card Fundamentals',
    status: 'Not started' as const,
    concepts: ['Credit Score', 'APR', 'Payment History'],
    xpReward: 180,
    estimatedTime: '18 min',
    assigned: false,
    classStatus: 'Not Started' as const,
  },
  {
    id: "4",
    title: 'Investment Basics',
    status: 'Not started' as const,
    concepts: ['Stocks', 'Bonds', 'Diversification'],
    xpReward: 250,
    estimatedTime: '25 min',
    assigned: false,
    classStatus: 'Not Started' as const,
  },
  {
    id: "5",
    title: 'Debt Management',
    status: 'Failed' as const,
    concepts: ['Debt Snowball', 'Debt Avalanche', 'Consolidation'],
    xpReward: 200,
    estimatedTime: '22 min',
    assigned: true,
    classStatus: 'In Progress' as const,
    dueDate: '2024-02-25',
  },
  {
    id: "6",
    title: 'Retirement Planning',
    status: 'Not started' as const,
    concepts: ['401k', 'IRA', 'Pension'],
    xpReward: 300,
    estimatedTime: '30 min',
    assigned: false,
    classStatus: 'Not Started' as const,
  },
];

export const students = [
  {
    id: "1",
    name: "Emily Chen",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emily",
    streak: 5,
    lastActivity: "2024-01-20",
    school: "Riverside Academy",
    badges: [
      { id: "1", name: "Budget Master", icon: "💰", type: "concept" as const },
      { id: "2", name: "Week Warrior", icon: "🔥", type: "streak" as const },
    ],
    masteryProgress: "85%",
  },
  {
    id: "2", 
    name: "Marcus Johnson",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus",
    streak: 12,
    lastActivity: "2024-01-21",
    school: "Riverside Academy",
    badges: [
      { id: "3", name: "Saving Star", icon: "⭐", type: "concept" as const },
    ],
    masteryProgress: "92%",
  },
  {
    id: "3", 
    name: "Sarah Kim",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    streak: 3,
    lastActivity: "2024-01-19",
    school: "Riverside Academy",
    badges: [
      { id: "4", name: "First Steps", icon: "🎯", type: "concept" as const },
    ],
    masteryProgress: "67%",
  },
  {
    id: "4", 
    name: "Alex Rodriguez",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    streak: 8,
    lastActivity: "2024-01-20",
    school: "Riverside Academy",
    badges: [
      { id: "5", name: "Streak Master", icon: "🔥", type: "streak" as const },
      { id: "6", name: "Credit Champion", icon: "💳", type: "concept" as const },
    ],
    masteryProgress: "78%",
  },
  {
    id: "5",
    name: "Sophie Miller",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie",
    streak: 6,
    lastActivity: "2024-01-21",
    school: "Riverside Academy",
    badges: [
      { id: "7", name: "Quiz Pro", icon: "🧠", type: "concept" as const },
    ],
    masteryProgress: "73%",
  },
  {
    id: "6",
    name: "David Thompson",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=David",
    streak: 1,
    lastActivity: "2024-01-22",
    school: "Riverside Academy",
    badges: [
      { id: "8", name: "First Steps", icon: "🎯", type: "concept" as const },
    ],
    masteryProgress: "42%",
  },
  {
    id: "7",
    name: "Luna Martinez",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Luna",
    streak: 9,
    lastActivity: "2024-01-21",
    school: "Riverside Academy",
    badges: [
      { id: "9", name: "Saving Star", icon: "⭐", type: "concept" as const },
      { id: "10", name: "Week Warrior", icon: "🔥", type: "streak" as const },
    ],
    masteryProgress: "88%",
  },
  {
    id: "8",
    name: "Ryan Clark",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ryan",
    streak: 4,
    lastActivity: "2024-01-20",
    school: "Riverside Academy",
    badges: [
      { id: "11", name: "Budget Master", icon: "💰", type: "concept" as const },
    ],
    masteryProgress: "65%",
  },
];

export const attempts = [
  {
    id: "1",
    episodeTitle: "Budget Basics",
    date: "2024-01-15",
    summary: "Completed budgeting exercise with 50/30/20 rule",
    score: 85,
  },
  {
    id: "2",
    episodeTitle: "Saving Strategies", 
    date: "2024-01-18",
    summary: "Learned about emergency funds and compound interest",
    score: 78,
  },
];

export const mentorInteractions = [
  {
    id: "1",
    question: "What's the difference between needs and wants?",
    answer: "Great question! Needs are essential things like food, shelter, and transportation. Wants are things you'd like to have but can live without, like entertainment or luxury items.",
  },
  {
    id: "2",
    question: "How much should I save each month?",
    answer: "The 50/30/20 rule suggests saving 20% of your income. Start with what you can afford, even if it's just $10 a month - building the habit is most important!",
  },
];

export const achievements = [
  {
    id: 1,
    title: 'First Steps',
    description: 'Complete your first episode',
    icon: '🎯',
    category: 'Progress',
    earned: true,
    earnedDate: new Date('2024-01-16'),
  },
  {
    id: 2,
    title: 'Week Warrior',
    description: 'Study for 7 consecutive days',
    icon: '🔥',
    category: 'Streak',
    earned: true,
    earnedDate: new Date('2024-01-22'),
  },
  {
    id: 3,
    title: 'Budget Master',
    description: 'Master all budgeting concepts',
    icon: '💰',
    category: 'Mastery',
    earned: false,
  },
];