// Simple PDF generation utility
export const generatePDF = (card: any) => {
  const content = `
${card.title}
${'-'.repeat(card.title.length)}

${card.steps ? card.steps.map((step: string, index: number) => 
  `${index + 1}. ${step}`
).join('\n') : ''}

${card.summary ? `\nSummary: ${card.summary}` : ''}

Generated by MoneyQuest AI Mentor
Date: ${new Date().toLocaleDateString('en-GB')}
  `.trim();

  // Create a blob with the text content
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  
  // Create download link
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${card.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.txt`;
  
  // Trigger download
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  // Clean up
  URL.revokeObjectURL(url);
};