// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vigkkapoydubvpnuxlxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpZ2trYXBveWR1YnZwbnV4bHhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMDE2ODgsImV4cCI6MjA3MTY3NzY4OH0.Mgo5k3F00i0zs3hlfJljdqjPgKcmhGW9B1ADYJLm6Zo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});